#!/usr/bin/env python3
"""Writes src/kept/unicode_tables.zig from the Unicode Character Database.

Decompositions and combining classes come from Python's unicodedata, simple
case foldings from CaseFolding.txt; both must be UNICODE_VERSION. Run from
the repository root:

    curl -fO https://www.unicode.org/Public/16.0.0/ucd/CaseFolding.txt
    python3 scripts/gen-unicode-tables.py CaseFolding.txt
"""

import subprocess
import sys
import unicodedata

UNICODE_VERSION = "16.0.0"
HANGUL_FIRST, HANGUL_LAST = 0xAC00, 0xD7A3


def scalars():
    for cp in range(0x110000):
        if 0xD800 <= cp <= 0xDFFF or HANGUL_FIRST <= cp <= HANGUL_LAST:
            continue
        yield cp


def simple_foldings(path):
    with open(path, encoding="utf-8") as fh:
        text = fh.read()
    header = f"# CaseFolding-{UNICODE_VERSION}.txt"
    if not text.startswith(header):
        sys.exit(f"{path}: expected a file starting {header!r}")
    folds = {}
    for line in text.splitlines():
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        code, status, mapping = [f.strip() for f in line.split(";")[:3]]
        if status in ("C", "S"):
            assert " " not in mapping
            folds[int(code, 16)] = int(mapping, 16)
    return folds


def emit_array(out, name, ty, values, per_row):
    out.append(f"pub const {name} = [_]{ty}{{\n")
    for i in range(0, len(values), per_row):
        row = ", ".join(f"0x{v:X}" for v in values[i : i + per_row])
        out.append(f"    {row},\n")
    out.append("};\n")


def emit_map(out, name, what, pairs):
    keys, offsets, vals = [], [], []
    for cp, seq in pairs:
        keys.append(cp)
        offsets.append(len(vals))
        vals.extend(seq)
    offsets.append(len(vals))
    out.append(f"\n/// Sorted scalars {what}.\n")
    emit_array(out, f"{name}_keys", "u21", keys, 8)
    out.append(
        f"\n/// Where the scalars of each `{name}_keys` entry start in"
        f" `{name}_vals`;\n/// the entry after it is where they end.\n"
    )
    emit_array(out, f"{name}_offsets", "u16", offsets, 12)
    out.append(f"\n/// The scalars of every `{name}_keys` entry, in key order.\n")
    emit_array(out, f"{name}_vals", "u21", vals, 8)


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    if unicodedata.unidata_version != UNICODE_VERSION:
        sys.exit(f"Python's unicodedata is {unicodedata.unidata_version}, expected {UNICODE_VERSION}")
    folds = simple_foldings(sys.argv[1])

    nfd, fold, ccc = [], [], []
    for cp in scalars():
        c = chr(cp)
        d = unicodedata.normalize("NFD", c)
        if d != c:
            nfd.append((cp, [ord(x) for x in d]))
        if cp in folds:
            fold.append((cp, [ord(x) for x in unicodedata.normalize("NFD", chr(folds[cp]))]))
        k = unicodedata.combining(c)
        if k:
            if ccc and ccc[-1][1] == cp - 1 and ccc[-1][2] == k:
                ccc[-1][1] = cp
            else:
                ccc.append([cp, cp, k])

    out = [
        "//! Canonical decompositions, simple case foldings, and canonical\n",
        f"//! combining classes from Unicode {UNICODE_VERSION}, generated by\n",
        "//! scripts/gen-unicode-tables.py. Hangul syllables are decomposed\n",
        "//! algorithmically and are absent here.\n",
    ]
    emit_map(out, "nfd", "with a canonical decomposition, each mapped to it", nfd)
    emit_map(
        out,
        "fold",
        "whose simple case folding (statuses C and S) differs\n/// from themselves, each mapped to that folding's canonical decomposition",
        fold,
    )
    out.append("\n/// `first, last, class` triples of nonzero combining class, sorted.\n")
    emit_array(out, "ccc_ranges", "u21", [v for r in ccc for v in r], 9)

    path = "src/kept/unicode_tables.zig"
    with open(path, "w") as fh:
        fh.write("".join(out))
    subprocess.run(["zig", "fmt", path], check=True)


if __name__ == "__main__":
    main()
